/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#ddb7ff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "background": "#f3fcef",
        "on-secondary-fixed-variant": "#004395",
        "secondary-fixed-dim": "#adc6ff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e2ebde",
        "primary-fixed": "#6bff8f",
        "on-primary-fixed-variant": "#005321",
        "surface-tint": "#006e2f",
        "secondary-container": "#2170e4",
        "on-primary-fixed": "#002109",
        "surface-bright": "#f3fcef",
        "surface": "#f3fcef",
        "tertiary": "#842bd2",
        "on-secondary-fixed": "#001a42",
        "on-error": "#ffffff",
        "surface-container-highest": "#dce5d9",
        "on-tertiary-container": "#5f00a3",
        "on-tertiary-fixed": "#2c0051",
        "surface-dim": "#d4ddd0",
        "secondary-fixed": "#d8e2ff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-container": "#004b1e",
        "outline-variant": "#bccbb9",
        "on-primary": "#ffffff",
        "surface-container-low": "#edf6ea",
        "on-tertiary-fixed-variant": "#6900b3",
        "secondary": "#0058be",
        "on-secondary-container": "#fefcff",
        "surface-container": "#e8f0e4",
        "on-background": "#161d16",
        "error-container": "#ffdad6",
        "primary-container": "#22c55e",
        "tertiary-fixed": "#f0dbff",
        "primary-fixed-dim": "#4ae176",
        "on-surface": "#161d16",
        "on-surface-variant": "#3d4a3d",
        "tertiary-container": "#cb94ff",
        "inverse-surface": "#2a322a",
        "inverse-on-surface": "#ebf3e7",
        "primary": "#006e2f",
        "outline": "#6d7b6c",
        "inverse-primary": "#4ae176",
        "surface-variant": "#dce5d9"
      },
      "borderRadius": {
        "xl": "16px",
      },
      "spacing": {
        "xl": "40px",
        "md": "16px",
        "sm": "8px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        "unit": "4px",
        "xs": "4px",
        "lg": "24px",
        "gutter": "24px"
      },
      "fontFamily": {
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg-mobile": ["Be Vietnam Pro", "sans-serif"],
        "display": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "character-display": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "character-display": ["64px", {"lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
